const countries = [
    { id: 1, name: 'Afghanistan', code: 'AF' },
    { id: 2, name: 'Åland Islands', code: 'AX' },
    { id: 3, name: 'Albania', code: 'AL' },
    { id: 4, name: 'Algeria', code: 'DZ' },
    { id: 5, name: 'American Samoa', code: 'AS' },
    { id: 6, name: 'AndorrA', code: 'AD' },
    { id: 7, name: 'Angola', code: 'AO' },
    { id: 8, name: 'Anguilla', code: 'AI' },
    { id: 9, name: 'Antarctica', code: 'AQ' },
    { id: 10, name: 'Antigua and Barbuda', code: 'AG' },
    { id: 11, name: 'Argentina', code: 'AR' },
    { id: 12, name: 'Armenia', code: 'AM' },
    { id: 13, name: 'Aruba', code: 'AW' },
    { id: 14, name: 'Australia', code: 'AU' },
    { id: 15, name: 'Austria', code: 'AT' },
    { id: 16, name: 'Azerbaijan', code: 'AZ' },
    { id: 17, name: 'Bahamas', code: 'BS' },
    { id: 18, name: 'Bahrain', code: 'BH' },
    { id: 19, name: 'Bangladesh', code: 'BD' },
    { id: 20, name: 'Barbados', code: 'BB' },
    { id: 21, name: 'Belarus', code: 'BY' },
    { id: 22, name: 'Belgium', code: 'BE' },
    { id: 23, name: 'Belize', code: 'BZ' },
    { id: 24, name: 'Benin', code: 'BJ' },
    { id: 25, name: 'Bermuda', code: 'BM' },
    { id: 26, name: 'Bhutan', code: 'BT' },
    { id: 27, name: 'Bolivia', code: 'BO' },
    { id: 28, name: 'Bosnia and Herzegovina', code: 'BA' },
    { id: 29, name: 'Botswana', code: 'BW' },
    { id: 30, name: 'Bouvet Island', code: 'BV' },
    { id: 31, name: 'Brazil', code: 'BR' },
    { id: 32, name: 'British Indian Ocean Territory', code: 'IO' },
    { id: 33, name: 'Brunei Darussalam', code: 'BN' },
    { id: 34, name: 'Bulgaria', code: 'BG' },
    { id: 35, name: 'Burkina Faso', code: 'BF' },
    { id: 36, name: 'Burundi', code: 'BI' },
    { id: 37, name: 'Cambodia', code: 'KH' },
    { id: 38, name: 'Cameroon', code: 'CM' },
]

export default countries;